# Generated by Django 4.2.1 on 2023-06-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('user_id', models.IntegerField()),
                ('review_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
