# Generated by Django 4.2.2 on 2023-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('grocery_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expiry_date', models.DateTimeField()),
                ('stocked_date', models.DateTimeField()),
                ('brand', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
