# Generated by Django 4.2.2 on 2023-07-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('vendor_id', models.IntegerField()),
            ],
        ),
    ]
