# Generated by Django 4.2.2 on 2023-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
