# Generated by Django 4.2.2 on 2023-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('review_content', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('author', models.CharField(max_length=25)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
